const States = {
    IDLE: "IDLE",
    AWAITING_CITY: "AWAITING_CITY",
    AWAITING_MANUAL_WEATHER: "AWAITING_MANUAL_WEATHER",
    AWAITING_MOOD: "AWAITING_MOOD",
    AWAITING_WINE_TYPE: "AWAITING_WINE_TYPE",
    AWAITING_WINE_SWEETNESS: "AWAITING_WINE_SWEETNESS",
    AWAITING_WINE_PRICE: "AWAITING_WINE_PRICE",
    GENERATING_RECOMMENDATION: "GENERATING_RECOMMENDATION",
    SOBRIETY_MENU: "SOBRIETY_MENU",
    SOBRIETY_CONFIRM_RESET: "SOBRIETY_CONFIRM_RESET",
  };
  
  const userStates = {};
  const sobrietyTracker = {};
  
  module.exports = { States, userStates, sobrietyTracker };